services:
  # Your Express Server
  api:
    build: .
    volumes:
      # Map host folder ./uploads to container folder /app/uploads
      - ./uploads:/app/uploads
    ports:
      - "5000:5000"
    environment:
      - PORT=${PORT}
      # Connect to the 'mongo' service defined below
      - DATABASE_URL=${DATABASE_URL}
      # Pass through other secrets (or use an .env file)
      - RESEND_API_KEY=${RESEND_API_KEY}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS}
      - NODE_ENV=${NODE_ENV}
      - LOG_LEVEL=${LOG_LEVEL}
      - FORCE_COLOR=${FORCE_COLOR}
      - LOG_EMOJI=${LOG_EMOJI}
    restart: always
