name: Auto merge development into main

on:
  pull_request:
    branches: ["development"]
    types: [closed]

jobs:
  merge-to-main:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Merge development into main
        uses: peter-evans/merge-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          head: development
          merge-method: squash
