name: Promote Dev to Main

on:
  push:
    branches: ["development"]

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Development
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for merging

      - name: Configure Git Bot
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Merge Development -> Main
        run: |
          git checkout main
          git pull origin main
          git merge origin/development
          git push origin main
